const quiz = [
{
	q:'The part of machine level instruction, which tells the central processor what has to be done, is',
	options:['Operation code','Address','Locator','Flip-Flop'],
	answer:0

},
{
	q:'Which of the following refers to the associative memory?',
	options:['the address of the data is generated by the CPU','the address of the data is supplied by the users','there is no need for an address i.e. the data is used as an address','the data are accessed sequentially'],
	answer:2

},

{
	q:'To avoid the race condition, the number of processes that may be simultaneously inside their critical section is',
	options:['8','1','16','0'],
	answer:1

},

{
	q:'A system program that combines the separately compiled modules of a program into a form suitable for execution',
	options:['assembler','linking loader','cross compiler','load and go'],
	answer:1

},

{
	q:'Process is',
	options:['program in High level language kept on disk','contents of main memory','a program in execution','a job in secondary memory'],
	answer:2

},

{
	q:'Interprocess communication',
	options:['is required for all processes','is usually done via disk drives','is never necessary,','allows processes to synchronize activity'],
	answer:3

},

{
	q:'Which of the following functions is(are) performed by the loader',
	options:['allocate space in memory for the programs and resolve symbolic references between object decks','adjust all address dependent locations, such as address constants, to correspond to the allocated space.','physically place the machine instructions and data into memory.','All of the above'],
	answer:3

},

{
	q:'User-Friendly Systems are:',
	options:['required for object-oriented programming','easy to develop','common among traditional mainframe operating systems','becoming more common'],
	answer:3

},


{
	q:'Which of the following addressing modes, facilitates access to an operand whose location is defined relative to the beginning of the data structure in which it appears?',
	options:['ascending','sorting','index','indirect'],
	answer:2

},

{
	q:'Page stealing',
	options:['is a sign of an efficient system','is taking page frames from other working sets','should be the tuning goal','is taking larger disk spaces for pages paged out'],
	answer:1

},

{
	q:'In MS-DOS 5.0, which is the number that acts as a code to uniquely identify the software product?',
	options:['MS','DOS','MS DOS','5.0'],
	answer:3

},

{
	q:'Bug means',
	options:['A logical error in a program','A difficult syntax error in a program','Documenting programs using an efficient documentation tool','All of the above'],
	answer:0

},

{
	q:'Memory management is :',
	options:['not used in modern operating system','replaced with virtual memory on current systems','not used on multiprogramming systems','critical for even the simplest operating systems'],
	answer:3

}
]

